### ISSUE TITLE
Revisar script DDL (optimizaciones)

### ISSUE THREAD

**Issue by ibarrancos** [carm-es/csvstorage#22]
Revisar con la gente de sistemas (base de datos) delante del Enterprise Manager, las sentencias más costosas y qué más SGA consumen, (explain plan menos óptimos), para **detectar los indices que faltarían por crear**, en base a las consultas más habituales.

**Comment by alp23g** [comment]
Todo ésto ya se realizó en la **migración**. 
Los **índices** que hemos considerado que **mejoran el rendimiento** de la aplicación están documentados en el **[issue 21](https://github.com/carm-es/csvstorage/issues/21)**.
También subo las sentencias DDL a **resources/scripts_bbdd/BDcsvstorage-Modificaciones Optimizar CSV Storage CARM BD.sql** en este **[commit](https://github.com/carm-es/csvstorage/commit/ecca053c530143af6fff56e244615a86b4f99e83)**
