### ISSUE TITLE
Fijar mismo directorio al guardar documento para el contenido (extensión _BF) y su fichero referencia 

### ISSUE THREAD

**Issue by ja-garcia** [carm-es/csvstorage#25]
Relacionado con #15 y #19, se nos están dando casos en los que al invocar a `guardarDocumento`, para documentos ENI y contra el endpoint *CSVDocumentMtomService* , el contenido (fichero con sufijo *_BF*) y su referencia (mismo nombre de fichero sin el sufijo *_BF*) van a parar a un directorio distinto en el almacenamiento, porque coincide un cambio de "partición" a mitad del alta del documento. Esto da problemas a la hora de recuperar el documento y es necesario parchear tal comportamiento para que el fichero *_BF* y el que lo referencia se guarden en el mismo directorio.

**Comment by alp23g** [comment]
Hemos detectado un **problema colateral**: Parece ser que los documentos que se quedaron **desemparejados** (antes de aplicar este parche) tienen la columna de BD **tamanio_fichero** de la tabla **csvst_documento a nulo**. Abro otro issue para resolverlo **#30**
